/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE master
GO

IF DB_ID('NC03_ORDERENTRY') IS NOT NULL
BEGIN
    ALTER DATABASE [NC03_ORDERENTRY]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [NC03_ORDERENTRY]
END
GO

CREATE DATABASE [NC03_ORDERENTRY]
GO
USE [NC03_ORDERENTRY]
GO

CREATE TABLE CUSTOMER ( -- CS
    CUSTOMER_IDENTIFIER CHAR(7),
    CUSTOMER_TELEPHONE_NUMBER VARCHAR(11),
    CUSTOMER_NAME NVARCHAR(100),
    CUSTOMER_STREET_ADDRESS NVARCHAR(100),
    CUSTOMER_CITY NVARCHAR(100),
    CUSTOMER_STATE NVARCHAR(100),
    CUSTOMER_ZIP_CODE VARCHAR(10),
    CUSTOMER_CREDIT_RATING INT,
    PREFERRED_CARD CHAR(7),

    CONSTRAINT PK_CUSTOMER
    PRIMARY KEY(CUSTOMER_IDENTIFIER),

    CONSTRAINT CHK_CUSTOMER_CUSTOMER_CREDIT_RATING
    CHECK (CUSTOMER_CREDIT_RATING >= 0)
)

CREATE TABLE CREDIT_CARD ( -- CD
    CUSTOMER_CREDIT_CARD_NUMBER CHAR(7),
    CUSTOMER_CREDIT_CARD_NAME NVARCHAR(100),
    PREFERRED_OPTION BIT,
    USAGE_COUNT INT,
    CUSTOMER_IDENTIFIER CHAR(7),

    CONSTRAINT PK_CREDIT_CARD
    PRIMARY KEY(CUSTOMER_CREDIT_CARD_NUMBER),

    CONSTRAINT FK_CREDIT_CARD_CUSTOMER
    FOREIGN KEY(CUSTOMER_IDENTIFIER)
    REFERENCES CUSTOMER,

    CONSTRAINT CHK_CREDIT_CARD_USAGE_COUNT
    CHECK (USAGE_COUNT >= 0)
)

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_CREDIT_CARD
    FOREIGN KEY(PREFERRED_CARD)
    REFERENCES CREDIT_CARD

CREATE TABLE ORDERS ( -- OD
    ORDER_NUMBER CHAR(7),
    CUSTOMER_TELEPHONE_NUMBER VARCHAR(11),
    ORDER_DATE DATE,
    SHIPPING_STREET_ADDRESS NVARCHAR(100),
    SHIPPING_CITY NVARCHAR(100),
    SHIPPING_STATE NVARCHAR(100),
    SHIPPING_ZIP_CODE VARCHAR(10),
    SHIPPING_DATE DATE,
    TOTAL_COST INT,
    CUSTOMER_IDENTIFIER CHAR(7),
    CUSTOMER_CREDIT_CARD_NUMBER CHAR(7),

    CONSTRAINT PK_ORDERS
    PRIMARY KEY(ORDER_NUMBER),

    CONSTRAINT FK_ORDERS_CUSTOMER
    FOREIGN KEY(CUSTOMER_IDENTIFIER)
    REFERENCES CUSTOMER,

    CONSTRAINT FK_ORDERS_CREDIT_CARD
    FOREIGN KEY(CUSTOMER_CREDIT_CARD_NUMBER)
    REFERENCES CREDIT_CARD,

    CONSTRAINT CHK_ORDERS_TOTAL_COST
    CHECK (TOTAL_COST >= 0)
)

CREATE TABLE ADVERTISED_ITEM ( -- IT
    ITEM_NUMBER CHAR(7),
    ITEM_DESCRIPTION NVARCHAR(200),
    ITEM_DEPARTMENT NVARCHAR(100),
    ITEM_WEIGHT INT,
    ITEM_COLOR NVARCHAR(50),
    ITEM_PRICE INT,
    LOWEST_PURCHASE_PRICE INT,

    CONSTRAINT PK_ADVERTISED_ITEM
    PRIMARY KEY(ITEM_NUMBER),

    CONSTRAINT CHK_ADVERTISED_ITEM_WEIGHT_PRICE_LOWPURPRICE
    CHECK (ITEM_WEIGHT >= 0 AND ITEM_PRICE >= 0
        AND LOWEST_PURCHASE_PRICE >= 0)
)

CREATE TABLE ORDERED_ITEM (
    ORDER_NUMBER CHAR(7),
    ITEM_NUMBER CHAR(7),
    QUANTITY_ORDERED INT,
    SELLING_PRICE INT,
    SHIPPING_DATE DATE,

    CONSTRAINT PK_ORDERED_ITEM
    PRIMARY KEY(ORDER_NUMBER, ITEM_NUMBER),

    CONSTRAINT FK_ORDERED_ITEM_ORDERS
    FOREIGN KEY(ORDER_NUMBER)
    REFERENCES ORDERS,

    CONSTRAINT FK_ORDERED_ITEM_ADVERTISED_ITEM
    FOREIGN KEY(ITEM_NUMBER)
    REFERENCES ADVERTISED_ITEM,

    CONSTRAINT CHK_ORDERED_ITEM_QUANTITY_SELLPRICE
    CHECK (QUANTITY_ORDERED >= 0 AND SELLING_PRICE >= 0)
)

CREATE TABLE SUPPLIER ( -- SP
    SUPPLIER_ID CHAR(7),
    SUPPLIER_NAME NVARCHAR(100),
    SUPPLIER_STREET_ADDRESS NVARCHAR(100),
    SUPPLIER_CITY NVARCHAR(100),
    SUPPLIER_STATE NVARCHAR(100),
    SUPPLIER_ZIP_CODE VARCHAR(10),

    CONSTRAINT PK_SUPPLIER
    PRIMARY KEY(SUPPLIER_ID)
)

CREATE TABLE RESTOCK_ITEM (
    SUPPLIER_ID CHAR(7),
    ITEM_NUMBER CHAR(7),
    PURCHASE_PRICE INT,

    CONSTRAINT PK_RESTOCK_ITEM
    PRIMARY KEY(SUPPLIER_ID, ITEM_NUMBER),

    CONSTRAINT FK_RESTOCK_ITEM_SUPPLIER
    FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIER,

    CONSTRAINT FK_RESTOCK_ITEM_ADVERTISED_ITEM
    FOREIGN KEY(ITEM_NUMBER)
    REFERENCES ADVERTISED_ITEM,

    CONSTRAINT CHK_RESTOCK_ITEM_PURCHASE_PRICE
    CHECK (PURCHASE_PRICE >= 0)
)

GO