/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_ORDERENTRY]
GO

-- CUSTOMER
CREATE INDEX IDX_CUSTOMER_PREFFERED_CARD
ON CUSTOMER(PREFERRED_CARD)

-- CREDIT_CARD
CREATE INDEX IDX_CREDIT_CARD_CUSTOMER_IDENTIFIER
ON CREDIT_CARD(CUSTOMER_IDENTIFIER)
INCLUDE(CUSTOMER_CREDIT_CARD_NAME, PREFERRED_OPTION, USAGE_COUNT)

-- ORDERS
CREATE INDEX IDX_ORDERS_CUSTOMER_IDENTIFIER_ORDER_NUMBER
ON ORDERS(CUSTOMER_IDENTIFIER, ORDER_NUMBER) INCLUDE(TOTAL_COST)