/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_ORDERENTRY]
GO

ALTER DATABASE [NC03_ORDERENTRY]
ADD FILEGROUP ORDERS_2021

ALTER DATABASE [NC03_ORDERENTRY]
ADD FILE
(
    NAME = PARTITION_ORDERS_2021,
    FILENAME = 'D:\SQLPartitions\PARTITION_ORDERS_2021.ndf',
    SIZE = 5MB,
    FILEGROWTH = 5MB
)
TO FILEGROUP ORDERS_2021;
GO

ALTER DATABASE [NC03_ORDERENTRY]
ADD FILEGROUP ORDERS_2022

ALTER DATABASE [NC03_ORDERENTRY]
ADD FILE
(
    NAME = PARTITION_ORDERS_2022,
    FILENAME = 'D:\SQLPartitions\PARTITION_ORDERS_2022.ndf',
    SIZE = 5MB,
    FILEGROWTH = 5MB
)
TO FILEGROUP ORDERS_2022;
GO

ALTER DATABASE [NC03_ORDERENTRY]
ADD FILEGROUP ORDERS_2023

ALTER DATABASE [NC03_ORDERENTRY]
ADD FILE
(
    NAME = PARTITION_ORDERS_2023,
    FILENAME = 'D:\SQLPartitions\PARTITION_ORDERS_2023.ndf',
    SIZE = 5MB,
    FILEGROWTH = 5MB
)
TO FILEGROUP ORDERS_2023;
GO

CREATE PARTITION FUNCTION PF_ORDERS_SHIPPING_DATE(DATE)
AS RANGE RIGHT FOR VALUES('2022/01/01', '2023/01/01')

CREATE PARTITION SCHEME SC_ORDERS_SHIPPING_DATE
AS PARTITION PF_ORDERS_SHIPPING_DATE
TO(ORDERS_2021, ORDERS_2022, ORDERS_2023)
GO

ALTER TABLE ORDERED_ITEM DROP CONSTRAINT FK_ORDERED_ITEM_ORDERS
ALTER TABLE ORDERS DROP CONSTRAINT PK_ORDERS

ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS
PRIMARY KEY NONCLUSTERED(ORDER_NUMBER ASC) ON [PRIMARY]

ALTER TABLE ORDERED_ITEM ADD CONSTRAINT FK_ORDERED_ITEM_ORDERS
FOREIGN KEY(ORDER_NUMBER) REFERENCES ORDERS

CREATE CLUSTERED INDEX IDX_ORDERS_SHIPPING_DATE
ON ORDERS(SHIPPING_DATE)
ON SC_ORDERS_SHIPPING_DATE(SHIPPING_DATE)
GO