/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_ORDERENTRY]
GO

CREATE OR ALTER PROC USP_ADVERTISED_ITEM_INS
    @ITEM_DESCRIPTION NVARCHAR(200),
    @ITEM_DEPARTMENT NVARCHAR(100),
    @ITEM_WEIGHT INT,
    @ITEM_COLOR NVARCHAR(50),
    @ITEM_PRICE INT,
    @ITEM_NUMBER CHAR(7) = NULL OUTPUT
AS BEGIN TRAN
    SELECT @ITEM_NUMBER = ITEM_NUMBER FROM ADVERTISED_ITEM
    WHERE ITEM_NUMBER = (SELECT MAX(ITEM_NUMBER) FROM ADVERTISED_ITEM)

    SET @ITEM_NUMBER = dbo.F_MAKE_ID('IT', @ITEM_NUMBER)

    INSERT INTO ADVERTISED_ITEM
    VALUES (@ITEM_NUMBER, @ITEM_DESCRIPTION, @ITEM_DEPARTMENT, @ITEM_WEIGHT,
        @ITEM_COLOR, @ITEM_PRICE, 0)
COMMIT TRAN
RETURN 0
GO